#!/usr/bin/env python3
"""Génère la version anglaise du portfolio (en/index.html) à partir de index.html.
Usage : python3 tools/portfolio-en.py   (chaque phrase doit être trouvée, sinon le script s'arrête)"""
import os, re, sys
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
s = open(os.path.join(ROOT, 'index.html'), encoding='utf-8').read()

T = [
# --- head ---
('<html lang="fr">', '<html lang="en">'),
('<meta name="description" content="Pierre Untas, développeur blockchain et full-stack. Un portfolio à visiter dans le hall de L\'Atrium : chaque vitrine présente un projet.">',
 '<meta name="description" content="Pierre Untas, blockchain and full-stack developer. A portfolio you walk through, in the hall of L\'Atrium: each display case holds a project.">'),
('<link rel="canonical" href="https://www.pierreuntas.com/">', '<link rel="canonical" href="https://www.pierreuntas.com/en/">'),
('<meta property="og:title" content="Pierre Untas · développeur blockchain et full-stack">', '<meta property="og:title" content="Pierre Untas · blockchain and full-stack developer">'),
('<meta property="og:description" content="Un portfolio à visiter dans le hall de L\'Atrium : chaque vitrine présente un projet.">', '<meta property="og:description" content="A portfolio you walk through, in the hall of L\'Atrium: each display case holds a project.">'),
('<meta property="og:url" content="https://www.pierreuntas.com/">', '<meta property="og:url" content="https://www.pierreuntas.com/en/">'),
('<meta property="og:locale" content="fr_FR">', '<meta property="og:locale" content="en_US">'),
('og-portfolio.jpg', 'og-portfolio-en.jpg'),
('<script id="langPick">', '<script id="langPick" data-off>'),
# --- page ---
('aria-label="Le hall de L\'Atrium : des colonnes, deux palmiers, un grand cristal, Pierre, Nonce, Gwei le chat et des vitrines qui présentent les projets de Pierre."',
 'aria-label="The hall of L\'Atrium: columns, two palm trees, a large crystal, Pierre, Nonce, Gwei the cat, and display cases presenting Pierre\'s projects."'),
('<span class="eyebrow" id="objHead">Objectif</span>', '<span class="eyebrow" id="objHead">Goal</span>'),
('aria-label="Couper le son"', 'aria-label="Mute"'),
('aria-label="Ouvrir le carnet des vitrines">Vitrines <b', 'aria-label="Open the list of display cases">Projects <b'),
('<p class="eyebrow">Portfolio · un Atrium à visiter</p>', '<p class="eyebrow">Portfolio · an Atrium to walk through</p>'),
('<p class="lede">Développeur blockchain et full-stack. Entre dans le hall : chaque vitrine garde un projet que j\'ai codé.</p>',
 '<p class="lede">Blockchain and full-stack developer. Step into the hall: each display case holds a project I built.</p>'),
('<span class="chip"><i></i>Ouvert aux missions Web3 et aux postes en remote</span>', '<span class="chip"><i></i>Open to Web3 freelance work and remote roles</span>'),
('id="enterBtn" type="button">Entrer</button>', 'id="enterBtn" type="button">Enter</button>'),
('id="fastBtn" type="button">Voir directement les projets</button>', 'id="fastBtn" type="button">Skip to the projects</button>'),
('<p class="hint">Touche le sol pour marcher. Touche quelqu\'un ou une vitrine pour en savoir plus.</p>', '<p class="hint">Tap the floor to walk. Tap someone or a display case to learn more.</p>'),
('<a class="lang" href="/en/?lang=en" hreflang="en" lang="en">English version</a>', '<a class="lang" href="/?lang=fr" hreflang="fr" lang="fr">Version française</a>'),
('· Bordeaux · remote international · Souris ou doigt : touche le sol pour marcher · Clavier : flèches ou ZQSD, Espace pour parler, V pour les vitrines, M pour le son',
 '· Bordeaux, France · remote worldwide · Mouse or finger: tap the floor to walk · Keyboard: arrows or WASD, Space to talk, V for the projects, M for sound'),
# --- fiches ---
("kind:'Qui je suis'", "kind:'Who I am'"),
("short:'Développeur blockchain et full-stack · Bordeaux · remote international.'", "short:'Blockchain and full-stack developer · Bordeaux, France · remote worldwide.'"),
("body:'Après sept ans à la tête d’une marque de mode et trois ans de développement full-stack en entreprise, je conçois aujourd’hui des applications blockchain. Mona Editions, ma plateforme de certification d’œuvres d’art en production sur Base, est née de ce croisement entre l’univers du design et les smart contracts.'",
 "body:'After seven years running a fashion brand and three years as a full-stack developer in industry, I now build blockchain applications. Mona Editions, my artwork certification platform live on Base, was born where design meets smart contracts.'"),
("facts:['Développeur full-stack chez Human Immobilier (2023 – 2026)', 'Certifié développeur blockchain par Alyra (2026)', 'Freelance Web3 depuis juin 2026']",
 "facts:['Full-stack developer at Human Immobilier (2023 – 2026)', 'Certified blockchain developer, Alyra (2026)', 'Web3 freelancer since June 2026']"),
("links:[['Mon parcours', '#parcours'], ['Me contacter', '#contact']]", "links:[['My background', '#parcours'], ['Contact me', '#contact']]"),
("kind:'Produit · smart contracts'", "kind:'Product · smart contracts'"),
("short:'Certifier une œuvre d’art physique avec un jeton, et donner au collectionneur un certificat qui le suit pour toujours.'",
 "short:'Certify a physical artwork with a token, and give the collector a certificate that follows it forever.'"),
("body:'Les artistes certifient et exposent leurs œuvres, et transfèrent le certificat lors d’une revente, sans portefeuille crypto. En scannant le QR code d’une œuvre, on voit son histoire : artiste, édition, provenance. Projet né pendant ma formation Alyra, aujourd’hui en production sur Base.'",
 "body:'Artists certify and showcase their work, and hand over the certificate when a piece is resold, with no crypto wallet needed. Scan an artwork’s QR code to see its story: artist, edition, provenance. Started during my Alyra training, now live on Base.'"),
("facts:['Smart contracts Solidity (ERC-1155) avec optimisation du gaz, tests sous Hardhat', 'Contrat vérifié sur Basescan, réclamation du certificat par QR code sécurisée par arbre de Merkle', 'Privy : connexion par e-mail, gaz sponsorisé, export de la clé privée', 'Front Next.js et TypeScript, stockage IPFS, déploiement sur Vercel', 'CI GitHub Actions : compilation et tests des contrats, build du front à chaque push et pull request']",
 "facts:['Gas-optimised Solidity smart contracts (ERC-1155), tested with Hardhat', 'Contract verified on Basescan; certificates claimed by QR code, secured with a Merkle tree', 'Privy: email sign-in, sponsored gas, private key export', 'Next.js and TypeScript front end, IPFS storage, deployed on Vercel', 'GitHub Actions CI: contracts compiled and tested, front end built on every push and pull request']"),
("['Voir le site', 'https://monaeditions.com'], ['Le contrat sur Basescan',", "['Visit the site', 'https://monaeditions.com'], ['The contract on Basescan',"),
("kind:'Application complète'", "kind:'Full-stack app'"),
("short:'Un cloud personnel décentralisé : fichiers sur IPFS, dossiers, notes et un LLM local.'", "short:'A decentralised personal cloud: files on IPFS, folders, notes and a local LLM.'"),
("body:'Les fichiers sont stockés sur IPFS, les métadonnées dans MongoDB. Une API REST en ASP.NET Core gère le stockage, et une interface Nuxt.js permet de créer des dossiers, d’envoyer des fichiers, d’écrire des notes et de discuter avec un modèle de langage qui tourne en local.'",
 "body:'Files are stored on IPFS and metadata in MongoDB. An ASP.NET Core REST API handles storage, and a Nuxt.js interface lets you create folders, upload files, write notes and chat with a language model running locally.'"),
("facts:['API REST en ASP.NET Core, métadonnées dans MongoDB', 'Stockage distribué sur IPFS', 'Interface Nuxt.js, LLM local intégré', 'Docker Compose et Prometheus']",
 "facts:['ASP.NET Core REST API, metadata in MongoDB', 'Distributed storage on IPFS', 'Nuxt.js interface with a built-in local LLM', 'Docker Compose and Prometheus']"),
("kind:'Jeu · pédagogie · développé avec l’IA'", "kind:'Game · learning · built with AI'"),
("short:'Le jeu dans lequel tu te trouves. Pour découvrir Ethereum sans rien installer.'", "short:'The game you are standing in. A way to discover Ethereum without installing anything.'"),
("body:'Dix chapitres dans ce hall : son premier coffre, les arnaques, les contrats, les validateurs, les frais, les ponts. En français et en anglais.'",
 "body:'Ten chapters in this hall: your first vault, scams, contracts, validators, fees, bridges. In French and English.'"),
("facts:['Moteur maison en Canvas 2D, musique générée en Web Audio', 'Sauvegarde locale, carnet du joueur, version anglaise complète', 'Tests de bout en bout avec Playwright']",
 "facts:['Custom Canvas 2D engine, music generated with Web Audio', 'Local save, player notebook, full English version', 'End-to-end tests with Playwright']"),
("['Jouer à L’Atrium', 'https://www.pierreuntas.com/game/']", "['Play L’Atrium', 'https://www.pierreuntas.com/game/?lang=en']"),
("kind:'Application de bureau · confidentialité'", "kind:'Desktop app · privacy'"),
("short:'Interroger Claude sur les pièces d’un dossier d’avocat, sans jamais envoyer de données confidentielles en clair.'",
 "short:'Ask Claude about the documents in a law firm’s case file, without ever sending confidential data in the clear.'"),
("body:'Une application de bureau pour un cabinet d’avocats : on choisit un dossier client dans le logiciel métier Secib, on coche des pièces, puis on demande à Claude un résumé, une chronologie ou des informations précises. Comme le demande le guide déontologique du CNB, les noms, adresses ou IBAN sont pseudonymisés sur l’ordinateur avant tout envoi, avec un écran de revue.'",
 "body:'A desktop app for a law firm: pick a client case in Secib, the firm’s practice management software, tick some documents, then ask Claude for a summary, a timeline or specific details. As the French bar’s ethics guidance requires, names, addresses and IBANs are pseudonymised on the computer before anything is sent, with a review screen.'"),
("facts:['Back-end en Rust (Tauri), interface en React et TypeScript', 'Module de pseudonymisation isolé : 11 catégories, IBAN et SIREN validés par clé, table de correspondance impossible à envoyer ou à écrire sur disque (garanti par un test de compilation)', 'Client HTTP pour l’API Secib : authentification, limite de concurrence, reprises avec backoff, testé contre un serveur simulé', 'Clé API chiffrée dans le trousseau système, journal local des envois']",
 "facts:['Rust back end (Tauri), React and TypeScript interface', 'Isolated pseudonymisation module: 11 categories, IBAN and SIREN checked by checksum, a mapping table that can never be sent or written to disk (enforced by a compile-time test)', 'HTTP client for the Secib API: authentication, concurrency limit, retries with backoff, tested against a mock server', 'API key encrypted in the system keychain, local log of everything sent']"),
("status:'Code privé · démo sur demande'", "status:'Private code · demo on request'"),
("kind:'Jeu multijoueur · développé avec l’IA'", "kind:'Multiplayer game · built with AI'"),
("short:'Un monde en blocs aux couleurs d’Ethereum, à construire entre amis dans le navigateur.'", "short:'A block world in Ethereum colours, to build with friends in the browser.'"),
("body:'On mine, on fabrique, on bâtit dans un monde infini généré au fil des pas. Chaque bloc se comporte comme un jeton : miner frappe, poser brûle, et chaque bloc posé porte le nom de son auteur. Prochaine étape : inscrire les objets uniques et les parcelles en smart contracts.'",
 "body:'Mine, craft and build in an endless world generated as you walk. Every block behaves like a token: mining mints, placing burns, and every placed block carries its builder’s name. Next step: putting unique items and land plots into smart contracts.'"),
("facts:['Rendu Three.js, textures pixel art générées en code, maillage des tronçons dans un Web Worker', 'Multijoueur en temps réel avec Supabase (Auth, Realtime, Postgres), parcelles, chat modéré', 'Le serveur fait autorité : chaque action passe par une fonction SQL qui vérifie les règles, la portée, le rythme et les déplacements', 'Jetons simulés : ERC-1155 pour les ressources, ERC-721 pour les objets uniques, registre des frappes et des brûlages', 'Une quarantaine de scénarios, dont les tentatives de triche, testés contre un vrai Postgres à chaque push']",
 "facts:['Three.js rendering, pixel-art textures generated in code, chunk meshing in a Web Worker', 'Real-time multiplayer with Supabase (Auth, Realtime, Postgres), land plots, moderated chat', 'Server-authoritative: every action goes through a SQL function that checks rules, reach, rate and movement', 'Simulated tokens: ERC-1155 for resources, ERC-721 for unique items, a ledger of mints and burns', 'Around forty scenarios, cheating attempts included, tested against a real Postgres on every push']"),
("status:'Lien de démo à venir'", "status:'Demo link coming soon'"),
# --- parcours ---
("['Janvier 2026 – aujourd’hui', 'Fondateur et développeur blockchain', 'Mona Editions · freelance depuis juin 2026', ['Plateforme de certification d’œuvres d’art physiques en production sur Base', 'Smart contracts Solidity (ERC-1155), tests Hardhat, contrat vérifié sur Basescan', 'Next.js, IPFS, Privy (e-mail, gaz sponsorisé), CI GitHub Actions'], true]",
 "['January 2026 – present', 'Founder and blockchain developer', 'Mona Editions · freelance since June 2026', ['Certification platform for physical artworks, live on Base', 'Solidity smart contracts (ERC-1155), Hardhat tests, contract verified on Basescan', 'Next.js, IPFS, Privy (email sign-in, sponsored gas), GitHub Actions CI'], true]"),
("['Juin 2023 – mai 2026', 'Développeur full-stack', 'Human Immobilier', ['Plusieurs produits du groupe : un ERP, un CRM, des sites web et des tâches planifiées', 'Back-end .NET Core et SQL Server, architecture DDD / CQRS ; front en Blazor et Vue.js', 'Tests unitaires, d’intégration et de validation ; monitoring Prometheus et Grafana ; Kanban sur Azure DevOps']]",
 "['June 2023 – May 2026', 'Full-stack developer', 'Human Immobilier · real estate group', ['Several of the group’s products: an ERP, a CRM, websites and scheduled jobs', '.NET Core and SQL Server back end, DDD / CQRS architecture; Blazor and Vue.js front ends', 'Unit, integration and acceptance tests; Prometheus and Grafana monitoring; Kanban on Azure DevOps']]"),
("['Janvier 2022 – janvier 2023', 'Fondateur', 'Minimal Miner', ['Conception, assemblage et vente de serveurs de minage crypto : mon premier contact avec la blockchain, à l’origine de ma reconversion']]",
 "['January 2022 – January 2023', 'Founder', 'Minimal Miner', ['Designed, assembled and sold crypto mining servers: my first contact with blockchain, and what led me to switch careers']]"),
("['Juillet 2016 – décembre 2022', 'Fondateur et président', 'Anders Arens · marque de mode de luxe', ['Conception et fabrication des collections, sourcing des fournisseurs et des ateliers', 'Vente en boutiques multimarques de luxe aux États-Unis, en Europe et au Japon, et en ligne', 'Recrutement d’agents commerciaux et d’investisseurs, salons professionnels et fashion weeks']]",
 "['July 2016 – December 2022', 'Founder and CEO', 'Anders Arens · luxury fashion brand', ['Designed and produced the collections, sourced suppliers and workshops', 'Sold through luxury multi-brand stores in the US, Europe and Japan, and online', 'Recruited sales agents and investors; trade shows and fashion weeks']]"),
("['Juillet 2025 – avril 2026', 'Certification Développeur Blockchain (RS6515)', 'Alyra, l’école blockchain · certifiée par France Compétences']",
 "['July 2025 – April 2026', 'Blockchain Developer certification (RS6515)', 'Alyra, the blockchain school · state-recognised by France Compétences']"),
("['Mars 2023 – mars 2024', 'Concepteur Développeur d’Applications', 'EPSI, école d’ingénierie informatique']", "['March 2023 – March 2024', 'Application Designer and Developer', 'EPSI, school of computer engineering']"),
("['Octobre – décembre 2022', 'Concepteur Développeur d’Applications', 'Le Wagon']", "['October – December 2022', 'Application Designer and Developer', 'Le Wagon, coding bootcamp']"),
("['Blockchain et Web3',", "['Blockchain and Web3',"),
("['Langages',", "['Languages',"),
("['Back-end et données',", "['Back end and data',"),
("['Outils',", "['Tools',"),
("const LANGS = 'Français natif · anglais professionnel';", "const LANGS = 'French (native) · English (professional)';"),
("const LIKES = ['Blockchain', 'IA', 'Surf', 'Bricolage', 'Couture'];", "const LIKES = ['Blockchain', 'AI', 'Surfing', 'DIY', 'Sewing'];"),
# --- HUD et objets ---
("label:'Nonce, le guide'", "label:'Nonce, the guide'"),
("setObjective('Parle à Pierre, près du cristal');", "setObjective('Talk to Pierre, by the crystal');"),
("setObjective(`Visite les vitrines · prochaine : ${P[nextGoal()].title}`);", "setObjective(`Visit the display cases · next: ${P[nextGoal()].title}`);"),
("setObjective('Tu as tout vu. Pierre aimerait avoir de tes nouvelles.');", "setObjective('You have seen everything. Pierre would love to hear from you.');"),
('aria-label="Fermer">×</button>', 'aria-label="Close">×</button>'),
# --- fiches parcours, contact, carnet ---
('<p class="eyebrow">Parcours</p><h3>Pierre Untas</h3><p><b>Développeur blockchain et full-stack</b></p>', '<p class="eyebrow">Background</p><h3>Pierre Untas</h3><p><b>Blockchain and full-stack developer</b></p>'),
('<p class="eyebrow">Expérience</p>', '<p class="eyebrow">Experience</p>'),
('<p class="eyebrow">Formation</p>', '<p class="eyebrow">Education</p>'),
('<p class="eyebrow">Compétences</p>', '<p class="eyebrow">Skills</p>'),
('<p class="eyebrow">Langues</p>', '<p class="eyebrow">Languages</p>'),
('<p class="eyebrow">Centres d’intérêt</p>', '<p class="eyebrow">Interests</p>'),
('<h3>Écris-moi</h3><p>Pour une mission, un poste en remote, ou simplement parler d’Ethereum.</p>', '<h3>Get in touch</h3><p>For freelance work, a remote role, or just to talk about Ethereum.</p>'),
('<li><b>E-mail</b> ·', '<li><b>Email</b> ·'),
('<li><b>Téléphone</b> ·', '<li><b>Phone</b> ·'),
('href="mailto:pierre.untas@gmail.com">M’écrire</a>', 'href="mailto:pierre.untas@gmail.com">Email me</a>'),
("$('copied').textContent = 'Pseudo copié'; } catch (e) { $('copied').textContent = 'Pseudo : pierreuntas'; }", "$('copied').textContent = 'Username copied'; } catch (e) { $('copied').textContent = 'Username: pierreuntas'; }"),
('<p class="eyebrow">Carnet de visite</p><h3>Les vitrines</h3><p>Touche un projet pour t’en approcher.</p>', '<p class="eyebrow">Visitor’s guide</p><h3>The display cases</h3><p>Tap a project to walk over to it.</p>'),
('id="bPath" type="button">Le parcours de Pierre</button>', 'id="bPath" type="button">Pierre’s background</button>'),
# --- dialogues ---
("'Salut, moi c’est Pierre, développeur blockchain et full-stack. Chaque vitrine garde un de mes projets, et le grand cristal, c’est L’Atrium : mon jeu pour découvrir Ethereum.' : 'Qu’est-ce qui t’intéresse ?', ['Ton parcours', 'Tes projets', 'Te contacter', 'Je visite']",
 "'Hi, I’m Pierre, a blockchain and full-stack developer. Each display case holds one of my projects, and the big crystal is L’Atrium: my game for discovering Ethereum.' : 'What would you like to know?', ['Your background', 'Your projects', 'Contact you', 'I’ll look around']"),
("'Sept ans à la tête d’une marque de mode, trois ans de full-stack en entreprise, et aujourd’hui la blockchain. Tout est dans la fiche.'", "'Seven years running a fashion brand, three years of full-stack in industry, and now blockchain. It’s all on the card.'"),
("'Commence par Mona Editions, juste là : c’est celui dont je suis le plus fier. Il tourne en production sur Base. Et va voir Secret Pro, à droite.'", "'Start with Mona Editions, right there: it’s the one I’m proudest of. It’s live on Base. And take a look at Secret Pro, on the right.'"),
("'Un e-mail, un appel ou un message sur LinkedIn : je réponds vite. GitHub pour le code.'", "'Email, call or message me on LinkedIn: I reply quickly. GitHub for the code.'"),
("'Tu as fait le tour de toutes les vitrines ! Si tu veux travailler avec Pierre, il est juste là. Demande-lui comment le contacter.'", "'You’ve seen every display case! If you’d like to work with Pierre, he’s right there. Ask him how to get in touch.'"),
("'D’habitude, j’accueille ici les nouveaux venus sur Ethereum. Aujourd’hui, je fais visiter le hall de Pierre.'", "'I usually welcome newcomers to Ethereum here. Today, I’m showing visitors around Pierre’s hall.'"),
("`Il te reste ${VISIT.length - seen.size} vitrine${VISIT.length - seen.size > 1 ? 's' : ''} à voir. Le carnet, en haut à droite, les liste toutes.` : 'Commence par parler à Pierre. Il est près du cristal.'",
 "`${VISIT.length - seen.size} display case${VISIT.length - seen.size > 1 ? 's' : ''} left to see. The list, top right, shows them all.` : 'Start by talking to Pierre. He’s by the crystal.'"),
("'Ce cristal, c’est tout l’Atrium : dix chapitres pour comprendre Ethereum, sans rien installer. Le lien est sur la fiche.'", "'This crystal is the whole Atrium: ten chapters to understand Ethereum, with nothing to install. The link is on the card.'"),
("'Mona Editions, c’est mon projet de fin de formation chez Alyra. Il est en production sur Base, avec un audit et 100 % de couverture de tests.'", "'Mona Editions was my final project at Alyra. It’s live on Base, audited, with 100% test coverage.'"),
("'Celui-là, je l’ai construit pour une avocate. Le plus délicat : garantir qu’aucun nom de client ne parte en clair. Tout est pseudonymisé sur l’ordinateur avant l’envoi.'", "'I built this one for a lawyer. The tricky part: making sure no client name ever leaves in the clear. Everything is pseudonymised on the computer before it’s sent.'"),
("'Mines d’Éther, je l’ai construit avec l’IA. La suite : inscrire les parcelles et les objets uniques en smart contracts. Le serveur en est déjà la source de vérité.'", "'I built Mines d’Éther with AI. Next: putting land plots and unique items into smart contracts. The server is already the source of truth.'"),
("'Lui, c’est Gwei, le chat de L’Atrium. Il ne fait rien, et il le fait très bien.'", "'That’s Gwei, L’Atrium’s cat. He does nothing, and he does it very well.'"),
("soundBtn.setAttribute('aria-label', m ? 'Activer le son' : 'Couper le son');", "soundBtn.setAttribute('aria-label', m ? 'Unmute' : 'Mute');"),
]
miss = [a[:90] for a, b in T if a not in s]
if miss: sys.exit('introuvable :\n' + '\n'.join(miss))
for a, b in T: s = s.replace(a, b)
os.makedirs(os.path.join(ROOT, 'en'), exist_ok=True)
open(os.path.join(ROOT, 'en', 'index.html'), 'w', encoding='utf-8').write(s)
# contrôle : du français qui traînerait dans le texte visible
k = s.index('/* =================== le portfolio')
body = s[s.index('<body>'):s.index('<script>', s.index('<body>'))] + s[k:]
left = [l.strip()[:140] for l in body.split('\n') if re.search(r"'[^']*[éèàùçê][^']*'|>[^<]*[éèàùçê][^<]*<", re.sub(r'/\*.*?\*/|//.*$', '', l)) and 'Mines d’Éther' not in l and 'Version française' not in l]
print('en/index.html écrit.', 'Reste à vérifier :' if left else '', *left, sep='\n')
